import { mod, assignModuleWeights } from '../helpers.js';

const MODULES = [
  mod(1, 'intro-cloud', 'Introduction Cloud', '☁️',
    ['cloud', 'iaas', 'paas', 'saas'],
    'Cloud = ressources à la demande — IaaS, PaaS, SaaS, modèle responsabilité partagée.',
    [{ title: 'Modèles', body: 'IaaS (VM), PaaS (Heroku), SaaS (Gmail) — elasticity, pay-as-you-go.' }],
    ['AWS Well-Architected'],
    { debutant: ['IaaS/PaaS/SaaS', 'Responsabilité partagée', 'Régions et AZ'],
      intermediaire: ['Comparatif providers', 'TCO estimé', 'Compliance régions'],
      professionnel: ['Multi-cloud strategy', 'FinOps', 'Cloud center of excellence'] }),

  mod(2, 'aws-cloud', 'AWS', '🟠',
    ['aws', 'ec2', 's3', 'lambda'],
    'Amazon Web Services — leader marché, écosystème complet.',
    [{ title: 'Services clés', body: 'EC2, S3, RDS, Lambda, VPC, IAM, CloudFront.' }],
    ['AWS', 'AWS Free Tier'],
    { debutant: ['Compte AWS', 'EC2 lancée', 'S3 bucket'],
      intermediaire: ['VPC configuré', 'IAM least privilege', 'RDS backup'],
      professionnel: ['Well-Architected review', 'Cost explorer', 'Organizations'] }),

  mod(3, 'azure-cloud', 'Azure', '🔵',
    ['azure', 'vm', 'blob', 'functions'],
    'Microsoft Azure — intégration entreprise Microsoft, hybrid cloud.',
    [{ title: 'Services', body: 'VM, Blob Storage, Azure SQL, Functions, AAD, ARM templates.' }],
    ['Azure Portal', 'Azure CLI'],
    { debutant: ['Compte Azure', 'VM déployée', 'Blob storage'],
      intermediaire: ['Resource groups', 'Azure AD', 'Cost management'],
      professionnel: ['Landing zones', 'Policy', 'Hybrid Arc'] }),

  mod(4, 'gcp-cloud', 'GCP', '🔴',
    ['gcp', 'gce', 'gcs', 'bigquery'],
    'Google Cloud — data analytics, Kubernetes (GKE), ML.',
    [{ title: 'Services', body: 'Compute Engine, Cloud Storage, GKE, Cloud Run, BigQuery.' }],
    ['GCP Console', 'gcloud CLI'],
    { debutant: ['Projet GCP', 'GCE instance', 'GCS bucket'],
      intermediaire: ['GKE cluster', 'IAM roles', 'Billing alerts'],
      professionnel: ['Anthos', 'Data pipeline', 'SCC security'] }),

  mod(5, 'vps-cloud', 'VPS', '🖥️',
    ['vps', 'hetzner', 'ovh', 'digitalocean'],
    'Serveur virtuel privé — contrôle total, bon rapport qualité/prix.',
    [{ title: 'Providers', body: 'Hetzner, OVH, DigitalOcean, Linode — critères CPU/RAM/bandwidth.' }],
    ['Hetzner', 'OVH', 'DigitalOcean'],
    { debutant: ['VPS provisionné', 'SSH configuré', 'Firewall actif'],
      intermediaire: ['Snapshots', 'Monitoring', 'Reverse DNS'],
      professionnel: ['HA multi-VPS', 'IaC provisioning', 'Disaster recovery'] }),

  mod(6, 'containers-cloud', 'Containers Cloud', '📦',
    ['ecs', 'cloud run', 'container apps', 'fargate'],
    'Exécuter conteneurs managés sans gérer les serveurs — Fargate, Cloud Run, ACA.',
    [{ title: 'Options', body: 'AWS ECS/Fargate, GCP Cloud Run, Azure Container Apps.' }],
    ['ECS', 'Cloud Run'],
    { debutant: ['Image push registry', 'Service conteneur déployé', 'URL publique'],
      intermediaire: ['Auto-scaling', 'Secrets injectés', 'Health checks'],
      professionnel: ['Multi-region', 'Service mesh', 'Cost optimization'] }),

  mod(7, 'serverless-cloud', 'Serverless', '⚡',
    ['lambda', 'functions', 'cloud functions', 'api gateway'],
    'Exécuter du code sans serveur — event-driven, scaling auto.',
    [{ title: 'Patterns', body: 'API Gateway + Lambda, triggers S3/SQS, cold starts, limits.' }],
    ['AWS Lambda', 'Vercel Functions'],
    { debutant: ['Hello Lambda', 'Trigger HTTP', 'Logs CloudWatch'],
      intermediaire: ['API Gateway', 'Dead letter queue', 'IAM fine-grained'],
      professionnel: ['Step Functions', 'Observability', 'FinOps serverless'] }),

  mod(8, 'cdn-cloud', 'CDN', '🌍',
    ['cdn', 'cloudfront', 'cloudflare', 'cache'],
    'CDN rapproche le contenu des utilisateurs — cache edge, SSL, DDoS protection.',
    [{ title: 'Bénéfices', body: 'Latence réduite, offload origin, cache invalidation, HTTPS.' }],
    ['Cloudflare', 'CloudFront', 'Fastly'],
    { debutant: ['CDN activé', 'Cache static assets', 'HTTPS edge'],
      intermediaire: ['Cache rules', 'Purge API', 'Analytics CDN'],
      professionnel: ['Multi-CDN', 'Edge compute', 'WAF CDN'] }),

  mod(9, 'stockage-cloud', 'Stockage', '💾',
    ['s3', 'blob', 'gcs', 'backup', 'archive'],
    'Stockage objet cloud — S3, versioning, lifecycle, glacier/archive.',
    [{ title: 'Bonnes pratiques', body: 'Versioning, encryption SSE, lifecycle rules, cross-region replication.' }],
    ['AWS S3', 'Azure Blob'],
    { debutant: ['Bucket créé', 'Upload fichiers', 'Permissions privées'],
      intermediaire: ['Versioning ON', 'Lifecycle glacier', 'Backup automatisé'],
      professionnel: ['Replication cross-region', 'Object lock', 'Inventory audits'] }),
];

assignModuleWeights(MODULES);
export const CLOUD_MODULES = MODULES;
