import { mod, assignModuleWeights } from '../helpers.js';

const MODULES = [
  mod(1, 'intro-cyber', 'Introduction cybersécurité', '🔐',
    ['cyber', 'sécurité', 'menace', 'risque'],
    'La cybersécurité protège les systèmes, données et utilisateurs contre les attaques numériques.',
    [{ title: 'Enjeux', body: 'Confidentialité, intégrité, disponibilité — triade CIA. Menaces internes/externes.' }],
    ['ANSSI', 'OWASP', 'CERT-FR'],
    { debutant: ['Triade CIA comprise', 'Menaces identifiées', 'Vocabulaire de base'],
      intermediaire: ['Cartographie risques', 'Politique sécurité esquissée', 'Veille cyber'],
      professionnel: ['Analyse de risques formalisée', 'Plan de continuité', 'Sensibilisation équipe'] }),

  mod(2, 'confidentialite', 'Confidentialité', '🔒',
    ['confidentialité', 'chiffrement', 'données'],
    'Garantir que seules les personnes autorisées accèdent aux informations.',
    [{ title: 'Mesures', body: 'Chiffrement au repos et en transit, classification des données, accès restreint.' }],
    ['TLS', 'AES', 'Bitwarden'],
    { debutant: ['HTTPS activé', 'Mots de passe forts', 'Données sensibles identifiées'],
      intermediaire: ['Chiffrement fichiers sensibles', 'Politique mots de passe', 'RGPD prise en compte'],
      professionnel: ['Classification données', 'Chiffrement bout en bout', 'Audit accès'] }),

  mod(3, 'integrite', 'Intégrité', '✅',
    ['intégrité', 'hash', 'signature'],
    'S\'assurer que les données n\'ont pas été modifiées sans autorisation.',
    [{ title: 'Contrôles', body: 'Hash SHA-256, signatures numériques, checksums, versioning.' }],
    ['OpenSSL', 'GPG'],
    { debutant: ['Hash compris', 'Checksums vérifiés', 'Backups testés'],
      intermediaire: ['Signatures sur releases', 'Contrôle intégrité BDD', 'Logs immuables'],
      professionnel: ['PKI en place', 'WORM storage si requis', 'Détection tampering'] }),

  mod(4, 'disponibilite', 'Disponibilité', '⏱️',
    ['disponibilité', 'ddos', 'backup', 'pRA'],
    'Les systèmes doivent rester accessibles aux utilisateurs autorisés.',
    [{ title: 'Résilience', body: 'Redondance, backups, PRA, protection DDoS, monitoring uptime.' }],
    ['UptimeRobot', 'Cloudflare'],
    { debutant: ['Backups configurés', 'Uptime monitoring', 'Plan incident basique'],
      intermediaire: ['PRA documenté', 'Restauration testée', 'SLA défini'],
      professionnel: ['Haute dispo', 'Failover testé', 'Exercices PRA annuels'] }),

  mod(5, 'authentification', 'Authentification', '👤',
    ['auth', 'login', 'session', 'jwt'],
    'Vérifier l\'identité d\'un utilisateur avant d\'accorder l\'accès.',
    [{ title: 'Mécanismes', body: 'Sessions, JWT, OAuth2, certificats, biométrie.' }],
    ['Keycloak', 'Auth0', 'Passport.js'],
    { debutant: ['Login/logout', 'Sessions sécurisées', 'Logout timeout'],
      intermediaire: ['JWT implémenté', 'Refresh tokens', 'Rate limiting login'],
      professionnel: ['OAuth2/OIDC', 'MFA obligatoire', 'Audit auth'] }),

  mod(6, 'mots-de-passe', 'Gestion des mots de passe', '🔑',
    ['password', 'bcrypt', 'argon2', 'hash'],
    'Les mots de passe restent la première ligne de défense — les stocker et les gérer correctement.',
    [{ title: 'Bonnes pratiques', body: 'Hash bcrypt/argon2, salt, politique complexité, gestionnaire de mots de passe.' }],
    ['Bitwarden', 'Have I Been Pwned'],
    { debutant: ['Jamais en clair', 'Hash bcrypt', 'Politique définie'],
      intermediaire: ['Argon2 si possible', 'Pwned check', 'Reset sécurisé'],
      professionnel: ['Rotation secrets', 'Vault', 'Zero trust auth'] }),

  mod(7, 'mfa', 'MFA', '📲',
    ['mfa', '2fa', 'totp', 'fido'],
    'L\'authentification multifacteur réduit drastiquement le risque de compromission de compte.',
    [{ title: 'Facteurs', body: 'Something you know/have/are — TOTP, SMS (moins sûr), FIDO2/WebAuthn.' }],
    ['Google Authenticator', 'YubiKey'],
    { debutant: ['2FA activé perso', 'TOTP compris', 'Codes backup'],
      intermediaire: ['MFA sur apps critiques', 'WebAuthn testé', 'Recovery process'],
      professionnel: ['MFA obligatoire org', 'Phishing-resistant', 'Audit MFA'] }),

  mod(8, 'phishing', 'Phishing', '🎣',
    ['phishing', 'ingénierie sociale', 'spear phishing'],
    'Le phishing trompe les utilisateurs pour voler identifiants ou installer des malwares.',
    [{ title: 'Défense', body: 'Formation, filtrage email, signalement, simulations phishing.' }],
    ['PhishTank', 'Mailsploit'],
    { debutant: ['Signes reconnus', 'Ne pas cliquer liens suspects', 'Vérifier expéditeur'],
      intermediaire: ['Simulation équipe', 'Filtrage SPF/DKIM/DMARC', 'Procédure signalement'],
      professionnel: ['Programme sensibilisation', 'Taux clic < 5%', 'Réponse incident phishing'] }),

  mod(9, 'malware-ransomware', 'Malware & Ransomware', '🦠',
    ['malware', 'ransomware', 'virus', 'trojan'],
    'Logiciels malveillants compromettent systèmes et données — le ransomware chiffre et extorque.',
    [{ title: 'Protection', body: 'Antivirus, EDR, patches, principe moindre privilège, backups offline.' }],
    ['VirusTotal', 'Windows Defender'],
    { debutant: ['Antivirus actif', 'Updates auto', 'Pas de USB inconnus'],
      intermediaire: ['EDR évalué', 'Segmentation réseau', 'Backups immuables'],
      professionnel: ['Plan réponse ransomware', 'Exercice tabletop', 'Assurance cyber'] }),

  mod(10, 'securite-web', 'Sécurité Web', '🌐',
    ['xss', 'csrf', 'injection', 'web'],
    'Les applications web sont la cible #1 — OWASP Top 10 est la référence.',
    [{ title: 'Vulnérabilités', body: 'XSS, CSRF, injection SQL, SSRF, broken access control.' }],
    ['OWASP ZAP', 'Burp Suite'],
    { debutant: ['HTTPS partout', 'Entrées filtrées', 'Headers sécurité'],
      intermediaire: ['Scan ZAP', 'CSP configuré', 'Prepared statements'],
      professionnel: ['Pentest', 'SAST/DAST CI', 'Bug bounty si pertinent'] }),

  mod(11, 'owasp', 'OWASP', '📋',
    ['owasp', 'top 10', 'asvs'],
    'OWASP fournit standards, guides et outils open source pour sécuriser les applications.',
    [{ title: 'Top 10', body: 'Injection, broken auth, XSS, misconfiguration, logging, etc.' }],
    ['OWASP', 'OWASP Cheat Sheets'],
    { debutant: ['Top 10 lu', '3 risques identifiés projet', 'Cheat sheets consultées'],
      intermediaire: ['ASVS niveau 1 visé', 'Revues code sécurité', 'Dépendances scannées'],
      professionnel: ['ASVS niveau 2+', 'Threat modeling', 'Security champions'] }),

  mod(12, 'osint', 'OSINT', '🔍',
    ['osint', 'reconnaissance', 'footprint'],
    'Open Source Intelligence — collecter des infos publiques pour évaluer la surface d\'attaque.',
    [{ title: 'Usage éthique', body: 'Recon passive, empreinte numérique, only authorized testing.' }],
    ['Shodan', 'theHarvester', 'Maltego'],
    { debutant: ['OSINT défini', 'Empreinte perso vérifiée', 'Éthique comprise'],
      intermediaire: ['Recon domaine autorisé', 'Rapport footprint', 'Données exposées corrigées'],
      professionnel: ['OSINT intégré pentest', 'Dark web monitoring', 'Brand protection'] }),

  mod(13, 'securite-reseau', 'Sécurité réseau', '🔥',
    ['firewall', 'vpn', 'segmentation', 'ids'],
    'Protéger le périmètre et le trafic réseau — firewall, VPN, segmentation, IDS/IPS.',
    [{ title: 'Contrôles', body: 'Firewall, VLAN DMZ, VPN site-to-site, zero trust network.' }],
    ['pfSense', 'WireGuard', 'Snort'],
    { debutant: ['Firewall activé', 'Ports minimaux', 'WiFi WPA3'],
      intermediaire: ['Segmentation VLAN', 'VPN configuré', 'Logs réseau'],
      professionnel: ['Zero trust', 'IDS/IPS', 'NAC'] }),

  mod(14, 'securite-linux', 'Sécurité Linux', '🐧',
    ['linux', 'hardening', 'selinux', 'fail2ban'],
    'Durcir les serveurs Linux — permissions, services, patches, fail2ban, audit.',
    [{ title: 'Hardening', body: 'Utilisateur non-root, SSH clés, désactiver services inutiles, auditd.' }],
    ['Lynis', 'fail2ban', 'CIS Benchmarks'],
    { debutant: ['SSH clés only', 'Updates auto', 'Utilisateur non-root'],
      intermediaire: ['fail2ban', 'Audit Lynis', 'SELinux/AppArmor'],
      professionnel: ['CIS hardening', 'CIS compliance', 'CIS audit automatisé'] }),

  mod(15, 'incident-response', 'Réponse aux incidents', '🚨',
    ['incident', 'soc', 'forensics', 'ir'],
    'Préparer et exécuter une réponse structurée face à un incident de sécurité.',
    [{ title: 'Processus', body: 'Détection, confinement, éradication, recovery, lessons learned.' }],
    ['NIST IR', 'SANS IR'],
    { debutant: ['Contacts incident listés', 'Procédure basique', 'Logs conservés'],
      intermediaire: ['Playbooks rédigés', 'Exercice simulé', 'Communication crise'],
      professionnel: ['SOC ou MSSP', 'Forensics ready', 'Post-mortem systématique'] }),
];

assignModuleWeights(MODULES);
export const CYBER_MODULES = MODULES;
