import { mod, assignModuleWeights } from '../helpers.js';

const MODULES = [
  mod(1, 'intro-devops', 'Introduction DevOps', '🔄',
    ['devops', 'ci/cd', 'culture', 'sre'],
    'DevOps rapproche dev et ops — livraisons fréquentes, automatisation, culture blameless.',
    [{ title: 'Piliers', body: 'Culture, automation, measurement, sharing — CALMS.' }],
    ['DORA metrics', 'The Phoenix Project'],
    { debutant: ['DevOps défini', 'CI vs CD', 'Bénéfices listés'],
      intermediaire: ['Pipeline esquissé', 'Métriques DORA', 'Post-mortem blameless'],
      professionnel: ['Platform engineering', 'SRE practices', 'DevOps maturity model'] }),

  mod(2, 'git-devops', 'Git', '📦',
    ['git', 'branch', 'merge', 'rebase'],
    'Git est le socle de toute chaîne DevOps — trunk-based ou GitFlow.',
    [{ title: 'Workflows', body: 'Feature branches, PR, conventional commits, tags semver.' }],
    ['Git', 'GitHub', 'GitLab'],
    { debutant: ['Commits atomiques', 'Branches', 'Merge basique'],
      intermediaire: ['Pull requests', 'Rebase vs merge', 'Tags release'],
      professionnel: ['Trunk-based', 'Signed commits', 'Monorepo tools'] }),

  mod(3, 'github-devops', 'GitHub', '🐙',
    ['github', 'actions', 'issues', 'projects'],
    'GitHub héberge code, CI (Actions), issues et revues.',
    [{ title: 'Features', body: 'Actions, branch protection, environments, secrets, Dependabot.' }],
    ['GitHub Actions', 'Dependabot'],
    { debutant: ['Repo GitHub', 'Issues utilisées', 'README complet'],
      intermediaire: ['Branch protection', 'Actions CI', 'Secrets configurés'],
      professionnel: ['Environments prod', 'CODEOWNERS', 'Security advisories'] }),

  mod(4, 'docker-devops', 'Docker', '🐳',
    ['docker', 'dockerfile', 'image', 'container'],
    'Conteneurs reproductibles — Dockerfile, images, registry, best practices.',
    [{ title: 'Dockerfile', body: 'Multi-stage, non-root, .dockerignore, healthcheck.' }],
    ['Docker', 'Docker Hub'],
    { debutant: ['Dockerfile fonctionnel', 'docker build/run', 'docker-compose dev'],
      intermediaire: ['Multi-stage', 'Scan images', 'Registry privé'],
      professionnel: ['Distroless images', 'SBOM', 'Policy as code'] }),

  mod(5, 'compose-devops', 'Docker Compose', '🎼',
    ['compose', 'stack', 'services', 'volumes'],
    'Orchestrer multi-conteneurs en dev/staging — réseaux, volumes, env.',
    [{ title: 'Compose v2', body: 'services, networks, volumes, depends_on, healthcheck.' }],
    ['Docker Compose'],
    { debutant: ['compose.yml 2 services', 'Volumes nommés', 'Ports mappés'],
      intermediaire: ['Override files', 'Secrets compose', 'Profiles'],
      professionnel: ['Prod-like staging', 'Observability sidecars', 'Resource limits'] }),

  mod(6, 'kubernetes-devops', 'Kubernetes', '☸️',
    ['kubernetes', 'k8s', 'pod', 'helm'],
    'Orchestrateur production — pods, deployments, services, ingress, Helm.',
    [{ title: 'Objets', body: 'Pod, Deployment, Service, Ingress, ConfigMap, Secret, Namespace.' }],
    ['Kubernetes', 'Helm', 'kubectl'],
    { debutant: ['kubectl basics', 'Pod déployé', 'Service ClusterIP'],
      intermediaire: ['Deployment rolling', 'Ingress TLS', 'Helm chart'],
      professionnel: ['GitOps ArgoCD', 'HPA/VPA', 'Network policies'] }),

  mod(7, 'cicd-devops', 'CI/CD', '⚡',
    ['ci', 'cd', 'pipeline', 'github actions'],
    'Automatiser build, test, deploy — quality gates et rollback.',
    [{ title: 'Pipeline', body: 'Lint → Test → Build → Scan → Deploy staging → Deploy prod.' }],
    ['GitHub Actions', 'GitLab CI'],
    { debutant: ['CI tests au push', 'Artefacts build', 'Deploy manuel doc'],
      intermediaire: ['CD staging auto', 'Notifications', 'Rollback script'],
      professionnel: ['Progressive delivery', 'Feature flags', 'DORA tracking'] }),

  mod(8, 'monitoring-devops', 'Monitoring', '📊',
    ['prometheus', 'grafana', 'alerting', 'slo'],
    'Observer prod — métriques, logs, traces, SLO/SLI, alerting.',
    [{ title: 'Stack', body: 'Prometheus + Grafana, Loki logs, Sentry errors, on-call.' }],
    ['Prometheus', 'Grafana', 'Sentry'],
    { debutant: ['Uptime check', 'Logs centralisés', 'Alertes email'],
      intermediaire: ['Dashboard Grafana', 'SLO définis', 'Runbooks'],
      professionnel: ['OpenTelemetry', 'Error budgets', 'Chaos engineering'] }),

  mod(9, 'iac-devops', 'Infrastructure as Code', '🏗️',
    ['terraform', 'ansible', 'iac', 'gitops'],
    'Versionner l\'infrastructure — Terraform, Ansible, Pulumi.',
    [{ title: 'Outils', body: 'Terraform plan/apply, Ansible playbooks, state remote, modules.' }],
    ['Terraform', 'Ansible', 'Pulumi'],
    { debutant: ['IaC concept', 'Premier .tf ou playbook', 'State local'],
      intermediaire: ['Modules Terraform', 'Remote state S3', 'CI plan'],
      professionnel: ['Policy as code', 'Drift detection', 'Multi-env workspaces'] }),
];

assignModuleWeights(MODULES);
export const DEVOPS_MODULES = MODULES;
