import { mod, assignModuleWeights } from '../helpers.js';

const MODULES = [
  mod(1, 'html-fondamentaux', 'HTML', '📄',
    ['html', 'sémantique', 'accessibilité', 'seo'],
    'HTML structure le contenu web. C\'est la base de tout site accessible et bien référencé.',
    [{ title: 'Sémantique', body: 'header, nav, main, article, section, footer — structure claire pour SEO et lecteurs d\'écran.' },
     { title: 'Formulaires', body: 'labels, types input, validation HTML5, autocomplete.' }],
    ['MDN HTML', 'W3C Validator', 'Can I Use'],
    { debutant: ['Structure de base créée', 'Titres et paragraphes', 'Liens fonctionnels'],
      intermediaire: ['Balises sémantiques utilisées', 'Formulaire accessible', 'Meta SEO'],
      professionnel: ['HTML validé W3C', 'Accessibilité de base', 'Landmarks ARIA si besoin'] }),

  mod(2, 'css-fondamentaux', 'CSS', '🎨',
    ['css', 'flexbox', 'grid', 'responsive'],
    'CSS contrôle la présentation. Flexbox et Grid permettent des layouts modernes et responsives.',
    [{ title: 'Layout', body: 'Flexbox pour alignements, Grid pour grilles complexes, media queries mobile-first.' }],
    ['MDN CSS', 'Flexbox Froggy', 'Grid Garden'],
    { debutant: ['Styles de base appliqués', 'Couleurs et typo', 'Espacements cohérents'],
      intermediaire: ['Flexbox maîtrisé', 'Responsive 3 breakpoints', 'Variables CSS'],
      professionnel: ['Design system CSS', 'Performance (pas de !important)', 'Print styles si besoin'] }),

  mod(3, 'javascript-fondamentaux', 'JavaScript', '⚡',
    ['javascript', 'dom', 'events', 'fetch'],
    'JavaScript rend les pages interactives — DOM, événements, async et fetch API.',
    [{ title: 'Fondamentaux', body: 'Variables, fonctions, tableaux, objets, modules ES6.' }],
    ['MDN JS', 'JavaScript.info'],
    { debutant: ['Variables et fonctions', 'Manipulation DOM basique', 'Événements click/submit'],
      intermediaire: ['Fetch API', 'Async/await', 'Modules ES6'],
      professionnel: ['Code structuré', 'Gestion erreurs', 'Pas de globals pollués'] }),

  mod(4, 'responsive-design', 'Responsive Design', '📱',
    ['responsive', 'mobile-first', 'breakpoints'],
    'Le responsive garantit une expérience optimale sur mobile, tablette et desktop.',
    [{ title: 'Mobile-first', body: 'Concevoir pour petit écran puis enrichir avec min-width.' }],
    ['Chrome DevTools', 'Responsively App'],
    { debutant: ['Viewport configuré', 'Images adaptatives', 'Menu mobile'],
      intermediaire: ['3+ breakpoints testés', 'Touch targets 44px', 'Pas de scroll horizontal'],
      professionnel: ['Tests devices réels', 'Performance mobile', 'Container queries si pertinent'] }),

  mod(5, 'accessibilite-web', 'Accessibilité', '♿',
    ['a11y', 'wcag', 'rgaa', 'aria'],
    'L\'accessibilité est obligatoire (RGAA) et élargit votre audience.',
    [{ title: 'WCAG', body: 'Contrastes, navigation clavier, labels, alternatives textuelles.' }],
    ['WAVE', 'axe DevTools', 'RGAA'],
    { debutant: ['Contrastes vérifiés', 'Alt sur images', 'Focus visible'],
      intermediaire: ['Navigation clavier complète', 'Labels formulaires', 'Hiérarchie titres'],
      professionnel: ['Audit RGAA niveau AA', 'Tests lecteur d\'écran', 'Plan de maintenance a11y'] }),

  mod(6, 'php-fondamentaux', 'PHP', '🐘',
    ['php', 'laravel', 'symfony', 'mvc'],
    'PHP reste dominant pour le web dynamique côté serveur en France.',
    [{ title: 'Bases', body: 'Syntaxe, includes, superglobals, PDO, sessions.' }],
    ['PHP.net', 'Laravel', 'Symfony'],
    { debutant: ['Page PHP dynamique', 'Formulaire traité', 'PDO connexion BDD'],
      intermediaire: ['Architecture MVC', 'Validation entrées', 'Sessions sécurisées'],
      professionnel: ['Framework choisi', 'Composer', 'Standards PSR'] }),

  mod(7, 'sql-fondamentaux', 'SQL', '🗄️',
    ['sql', 'mysql', 'postgresql', 'requêtes'],
    'SQL interroge et modifie les données relationnelles — compétence transversale essentielle.',
    [{ title: 'Requêtes', body: 'SELECT, JOIN, GROUP BY, INSERT, UPDATE, DELETE, transactions.' }],
    ['PostgreSQL', 'MySQL', 'DBeaver'],
    { debutant: ['SELECT basiques', 'INSERT/UPDATE', 'Clé primaire'],
      intermediaire: ['JOIN maîtrisés', 'Contraintes FK', 'Index'],
      professionnel: ['Requêtes optimisées', 'Migrations', 'Normalisation'] }),

  mod(8, 'api-rest', 'API REST', '🔌',
    ['api', 'rest', 'json', 'http'],
    'Les API REST connectent frontend et backend, mobile et services tiers.',
    [{ title: 'Principes REST', body: 'Ressources, verbes HTTP, codes statut, JSON, versioning.' }],
    ['Postman', 'Swagger', 'OpenAPI'],
    { debutant: ['Endpoint GET/POST', 'JSON responses', 'Codes HTTP basiques'],
      intermediaire: ['CRUD complet', 'Validation', 'Documentation Swagger'],
      professionnel: ['Auth API', 'Versioning', 'Tests automatisés API'] }),

  mod(9, 'git-fondamentaux', 'Git', '📦',
    ['git', 'github', 'branch', 'commit'],
    'Git versionne le code — indispensable en équipe et pour le titre DWWM.',
    [{ title: 'Workflow', body: 'commit, branch, merge, pull request, résolution conflits.' }],
    ['Git', 'GitHub', 'GitLab'],
    { debutant: ['Repo initialisé', 'Commits réguliers', 'Push GitHub'],
      intermediaire: ['Branches feature', 'Pull requests', '.gitignore'],
      professionnel: ['Conventional commits', 'Protection main', 'Review code'] }),

  mod(10, 'deploiement-web', 'Déploiement', '🚀',
    ['deploy', 'vercel', 'ovh', 'ssl'],
    'Mettre en ligne un site DWWM — hébergement, domaine, SSL.',
    [{ title: 'Hébergement', body: 'Mutualisé, VPS, PaaS — critères coût et simplicité.' }],
    ['Vercel', 'Netlify', 'OVH'],
    { debutant: ['Site en ligne', 'URL publique', 'HTTPS'],
      intermediaire: ['Env prod', 'Domaine configuré', 'FTP/SFTP ou CI deploy'],
      professionnel: ['Deploy documenté', 'Rollback possible', 'Monitoring basique'] }),
];

assignModuleWeights(MODULES);
export const DWWM_MODULES = MODULES;
