import { mod, assignModuleWeights } from '../helpers.js';

const MODULES = [
  mod(1, 'fs-linux', 'Système de fichiers', '📁',
    ['ext4', 'inode', 'mount', 'fstab'],
    'Linux organise les données en arborescence — /, /home, /var, /etc, montages et permissions.',
    [{ title: 'Hiérarchie FHS', body: '/bin, /etc, /var/log, /tmp — Filesystem Hierarchy Standard.' }],
    ['man pages', 'lsblk'],
    { debutant: ['Navigation cd/ls', 'Chemins absolus/relatifs', 'Arborescence /'],
      intermediaire: ['Partitions et mount', 'fstab', 'df/du'],
      professionnel: ['LVM', 'Quotas', 'Snapshots'] }),

  mod(2, 'permissions-linux', 'Permissions', '🔐',
    ['chmod', 'chown', 'rwx', 'umask'],
    'rwx pour user/group/other — base de la sécurité fichiers Linux.',
    [{ title: 'Octal', body: '755, 644, chmod/chown/chgrp, umask, ACL si besoin.' }],
    ['chmod calc'],
    { debutant: ['ls -l lu', 'chmod basique', 'chown compris'],
      intermediaire: ['umask configuré', 'ACL testées', 'Sticky bit'],
      professionnel: ['Audit permissions', 'Principe moindre privilège', 'SELinux contexts'] }),

  mod(3, 'utilisateurs-linux', 'Utilisateurs', '👤',
    ['useradd', 'passwd', 'sudo', '/etc/passwd'],
    'Comptes locaux, groupes, sudo — gestion identités serveur.',
    [{ title: 'Fichiers', body: '/etc/passwd, /etc/shadow, /etc/group, visudo.' }],
    ['useradd', 'sudo'],
    { debutant: ['useradd/usermod', 'sudo configuré', 'Pas de root direct'],
      intermediaire: ['Groupes secondaires', 'Password policy', 'Login défaut désactivé'],
      professionnel: ['LDAP/SSO', 'Audit comptes', 'Rotation comptes service'] }),

  mod(4, 'groupes-linux', 'Groupes', '👥',
    ['groupadd', 'gpasswd', 'sgid'],
    'Les groupes partagent permissions — projet dev, www-data, docker.',
    [{ title: 'Usage', body: 'groupadd, usermod -aG, SGID répertoires partagés.' }],
    ['groups', 'id'],
    { debutant: ['Groupes listés', 'Ajout au groupe', 'Permissions groupe'],
      intermediaire: ['SGID répertoire', 'Groupe docker', 'Documentation groupes'],
      professionnel: ['RBAC fichiers', 'Revues groupes trimestrielles', 'Automatisation'] }),

  mod(5, 'ssh-linux', 'SSH', '🔑',
    ['ssh', 'scp', 'sftp', 'clé publique'],
    'SSH administre les serveurs à distance — clés, config durcie, pas de root login.',
    [{ title: 'Durcissement', body: 'Clés ed25519, PasswordAuthentication no, AllowUsers, fail2ban.' }],
    ['OpenSSH', 'fail2ban'],
    { debutant: ['Connexion ssh', 'Clé publique générée', 'scp fichier'],
      intermediaire: ['Config /etc/ssh/sshd_config', 'fail2ban', 'Bastion jump host'],
      professionnel: ['SSH certificates', 'Audit connexions', 'MFA SSH'] }),

  mod(6, 'processus-linux', 'Processus', '⚙️',
    ['ps', 'top', 'systemd', 'kill'],
    'Processus, signaux, priorités — systemd gère services modernes.',
    [{ title: 'Commandes', body: 'ps aux, top/htop, kill -15/-9, nice, renice, systemd.' }],
    ['htop', 'systemctl'],
    { debutant: ['ps et top', 'Kill processus', 'systemctl status'],
      intermediaire: ['Unit files systemd', 'Logs journalctl', 'Limites ressources'],
      professionnel: ['Cgroups', 'Auto-restart policies', 'Profiling perf'] }),

  mod(7, 'services-linux', 'Services', '🔄',
    ['systemd', 'service', 'enable', 'cron'],
    'Services au démarrage — nginx, postgresql, cron jobs.',
    [{ title: 'systemd', body: 'systemctl start/stop/enable, timers, dependencies.' }],
    ['systemd', 'cron'],
    { debutant: ['start/stop service', 'enable au boot', 'cron basique'],
      intermediaire: ['Unit custom', 'Timers systemd', 'Logrotate'],
      professionnel: ['Dependency graph', 'Zero-downtime reload', 'IaC services'] }),

  mod(8, 'bash-linux', 'Bash', '💻',
    ['bash', 'script', 'grep', 'awk', 'sed'],
    'Automatiser avec Bash — scripts, pipelines, grep/awk/sed.',
    [{ title: 'Scripts', body: 'Shebang, variables, if/for, functions, exit codes, shellcheck.' }],
    ['ShellCheck', 'bash manual'],
    { debutant: ['Script hello', 'Variables', 'if/for'],
      intermediaire: ['Functions', 'Arguments', 'grep/awk/sed'],
      professionnel: ['Scripts idempotents', 'CI lint shellcheck', 'Bibliothèque scripts'] }),

  mod(9, 'logs-linux', 'Logs', '📋',
    ['journalctl', 'syslog', 'logrotate', '/var/log'],
    'Centraliser et analyser logs — journald, rsyslog, ELK.',
    [{ title: 'Emplacements', body: '/var/log, journalctl -u nginx, logrotate, retention.' }],
    ['journalctl', 'rsyslog', 'Loki'],
    { debutant: ['tail -f logs', 'journalctl basique', 'Rotation comprise'],
      intermediaire: ['Logrotate config', 'Centralisation', 'Alertes erreurs'],
      professionnel: ['ELK/Loki stack', 'SIEM integration', 'Retention compliance'] }),

  mod(10, 'securite-linux', 'Sécurité Linux', '🛡️',
    ['hardening', 'lynis', 'audit', 'patch'],
    'Durcissement serveur — patches, CIS benchmarks, audit Lynis.',
    [{ title: 'Checklist', body: 'Updates auto, firewall ufw, fail2ban, désactiver services inutiles.' }],
    ['Lynis', 'ufw', 'CIS'],
    { debutant: ['Updates auto', 'ufw activé', 'SSH durci'],
      intermediaire: ['Lynis audit', 'CIS appliqué', 'AppArmor'],
      professionnel: ['Compliance automatisée', 'Intrusion detection', 'Patch SLA'] }),
];

assignModuleWeights(MODULES);
export const LINUX_MODULES = MODULES;
