/** Types de réseaux — contenu détaillé */

export const NETWORK_TYPES = [
  {
    id: 'pan', abbr: 'PAN', name: 'Personal Area Network',
    definition: 'Réseau personnel couvrant quelques mètres — périphériques d\'une personne.',
    schema: 'Smartphone ↔ Montre ↔ Écouteurs\n(Bluetooth / USB)',
    useCases: ['Sync wearables', 'Partage fichiers local', 'IoT personnel'],
    pros: ['Faible consommation', 'Simple', 'Pas d\'infrastructure'],
    cons: ['Portée très limitée', 'Sécurité Bluetooth variable'],
    example: 'Apple Watch synchronisée avec iPhone via Bluetooth.',
    checklist: ['Appairage sécurisé', 'Bluetooth désactivé si inutilisé', 'Mises à jour firmware'],
  },
  {
    id: 'lan', abbr: 'LAN', name: 'Local Area Network',
    definition: 'Réseau local — bureau, maison, petit bâtiment (Ethernet/WiFi).',
    schema: 'PC₁ ─ Switch ─ PC₂\n         │\n      Routeur → Internet',
    useCases: ['Partage imprimante', 'NAS maison', 'LAN party', 'Bureau PME'],
    pros: ['Haut débit', 'Faible latence', 'Contrôle local'],
    cons: ['Portée limitée au bâtiment', 'Câblage coûteux en grande échelle'],
    example: 'Réseau Ethernet d\'une startup de 20 postes + WiFi invités.',
    checklist: ['VLAN invités séparé', 'Switch managé', 'Adressage IP documenté'],
  },
  {
    id: 'wlan', abbr: 'WLAN', name: 'Wireless LAN',
    definition: 'LAN sans fil basé sur WiFi (IEEE 802.11).',
    schema: 'Clients WiFi → Point d\'accès → Switch → Routeur',
    useCases: ['Mobilité bureau', 'Hotspot public', 'IoT WiFi'],
    pros: ['Mobilité', 'Déploiement rapide', 'Moins de câbles'],
    cons: ['Interférences', 'Sécurité WiFi à configurer', 'Portée variable'],
    example: 'WiFi entreprise WPA3-Enterprise avec RADIUS.',
    checklist: ['WPA3 ou WPA2-Enterprise', 'SSID invité isolé', 'Canal optimisé'],
  },
  {
    id: 'can', abbr: 'CAN', name: 'Campus Area Network',
    definition: 'Réseau interconnectant plusieurs bâtiments d\'un même campus.',
    schema: 'Bât.A ← Fibre → Bât.B ← Fibre → Bât.C',
    useCases: ['Université', 'Hôpital', 'Grand site industriel'],
    pros: ['Mutualisation services', 'Administration centralisée'],
    cons: ['Coût fibre', 'Single point of failure sans redondance'],
    example: 'Réseau universitaire reliant facultés sur 5 km.',
    checklist: ['Redondance liens', 'Cartographie campus', 'QoS VoIP'],
  },
  {
    id: 'man', abbr: 'MAN', name: 'Metropolitan Area Network',
    definition: 'Réseau métropolitain couvrant une ville ou agglomération.',
    schema: 'Zone ville — FAI / opérateur métro Ethernet',
    useCases: ['FAI local', 'Caméras ville', 'Interconnexion datacenters ville'],
    pros: ['Couverture urbaine', 'Débit élevé métro'],
    cons: ['Coût opérateur', 'Dépendance fournisseur'],
    example: 'Metro Ethernet reliant succursales bancaires intra-muros.',
    checklist: ['SLA opérateur', 'Diverse routing', 'Monitoring latence'],
  },
  {
    id: 'wan', abbr: 'WAN', name: 'Wide Area Network',
    definition: 'Réseau étendu — interconnecte sites géographiquement distants.',
    schema: 'Siège Paris ← MPLS/Internet → Agence Lyon → Cloud AWS',
    useCases: ['Multinationale', 'Teleworking HQ', 'CDN global'],
    pros: ['Connectivité mondiale', 'Cloud hybrid'],
    cons: ['Latence', 'Coût bande passante', 'Complexité routing'],
    example: 'MPLS reliant 50 sites d\'une ESN en France.',
    checklist: ['VPN site-to-site', 'SD-WAN évalué', 'Optimisation latence'],
  },
  {
    id: 'san', abbr: 'SAN', name: 'Storage Area Network',
    definition: 'Réseau dédié au stockage bloc haute performance (Fibre Channel, iSCSI).',
    schema: 'Serveurs → Switch SAN → Baies stockage',
    useCases: ['Datacenter', 'Virtualisation VMware', 'Bases critiques'],
    pros: ['Performance I/O', 'Centralisation stockage', 'Snapshots'],
    cons: ['Coût élevé', 'Expertise requise'],
    example: 'SAN Fibre Channel pour cluster SQL Server.',
    checklist: ['Zoning FC', 'Multipath I/O', 'Réplication synchrone'],
  },
  {
    id: 'vpn', abbr: 'VPN', name: 'Virtual Private Network',
    definition: 'Tunnel chiffré créant un réseau privé virtuel sur Internet public.',
    schema: 'Remote Worker → VPN tunnel → Réseau entreprise',
    useCases: ['Télétravail', 'Accès admin distant', 'Site-to-site'],
    pros: ['Chiffrement', 'Accès distant sécurisé', 'Coût vs MPLS'],
    cons: ['Performance variable', 'Configuration PKI', 'Single VPN gateway'],
    example: 'WireGuard VPN pour accès SSH aux serveurs prod.',
    checklist: ['MFA sur VPN', 'Split tunneling policy', 'Logs connexions'],
  },
];
